### ISSUE TITLE
[Question] Sumber data ?

### ISSUE THREAD

**Issue by idiotnesia1945** [ichadhr/db-wilayah-indonesia#1]
Ini keren btw, kodepos udah di mapping berdasarkan kelurahan. Datanya dapet dari mana kak ? untuk keperluan update bagaimana ?

**Comment by idiotnesia1945** [comment]
@ichadhr kalo dilihat dari [sini](https://github.com/edwardsamuel/Wilayah-Administratif-Indonesia/blob/master/csv/districts.csv) ada total 514 kabupaten/kota di indonesia sementara disini cuma 501, di [wikipedia](https://id.wikipedia.org/wiki/Daftar_kabupaten_dan_kota_di_Indonesia) pun 514

**Comment by ichadhr** [comment]
> @ichadhr kalo dilihat dari sini ada total 514 kabupaten/kota di indonesia sementara disini cuma 501, di wikipedia pun 514

Yup, sepertinya ada kekurangan 😣 untuk kabupaten/kota saya ambil refrensi dari [BSN](http://www.big.go.id/assets/download/sni/SNI/17.%20SNI%207657-2010%20Singkatan%20nama%20kota.pdf), saya akan coba kroscek ulang, thanks

**Comment by sugenk** [comment]
ini masih agak ngawur data mapping kabkot ke provinsinya...
saya cek misal kabupaten bojonegoro punya id provinsi 12 = jawa barat
lalu saya cek provinsi jatim id=15 mana saja kabupatennya juga masih salah.

untuk data dari kulurahan -> kecamatan -> kabkot kayaknya betul, belum cek semua.
