### ISSUE TITLE
Mapping provinsi_id di tbl_kabkot masih miss match !

### ISSUE THREAD

**Issue by sugenk** [ichadhr/db-wilayah-indonesia#2]
ini masih agak ngawur data mapping kabkot ke provinsinya...
saya cek misal kabupaten bojonegoro punya id provinsi 12 = jawa barat
lalu saya cek provinsi jatim id=15 mana saja kabupatennya juga masih salah.

untuk data dari kulurahan -> kecamatan -> kabkot kayaknya betul, belum cek semua.

**Comment by ichadhr** [comment]
my mistake, saya lupa melakukan mapping ID provinsi pada table kabkot karena sebelumnya daftar provinsi tersusun berdasarkan alphabet.. thanks koreksinya

**Comment by zho** [comment]
kabupaten badung, sumatra utara
