### ISSUE TITLE
ibukota provinsi

### ISSUE THREAD

**Issue by 85degree** [ichadhr/db-wilayah-indonesia#5]
Halo mas,

Dalam tabel KabKota kan terdapat Ibukota yang dimana isinya adalah kecamatan pusat administratif pemerintahan dalam sebuah kabupaten/kota. Ya walaupun pada praktiknya ndak selalu begitu sih...

Mengapa provinsi tidak ada ibukotanya? Sengaja atau memang ada keperluan khusus sehingga ibukota provinsi tidak ada? Kalau berkenan, nanti saya coba submit pull request yang ada ibukota ya

Salam

**Comment by ichadhr** [comment]
halo mas, silahkan ditambahkan.. karna saat data ini dibuat saya _belum_ ada keperluan untuk data ibukota provinsi

**Comment by 85degree** [comment]
#6 mohon cek mas.. tengkyu

**Comment by ichadhr** [comment]
thank you mas
